# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "738917b0b749fefbe1ad112fb1717d5a"
name = "NQ-Shoppable-Claura"
application_url = "https://claura-shoppable.vercel.app"
embedded = true

[access_scopes]
scopes = "read_files,write_files,read_product_listings,write_product_listings,read_products,write_products,read_script_tags,write_script_tags,read_themes,write_themes,read_orders,write_pixels,read_customer_events"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

[auth]
redirect_urls = [
  "https://claura-shoppable.vercel.app/auth/callback",
  "https://claura-shoppable.vercel.app/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true